spring:
    application:
        name: admin-gate
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    redis:
        database: 1
        host: 127.0.0.1
        pool:
            max-active: 20
    boot:
      admin:
        url: http://localhost:8764/
server:
    port: 8765 #启动端口
#
zuul:
  routes:
    back:
      path: /back/**
      serviceId: admin-service

    ui:
      path: /admin/**
      serviceId: admin-ui


ribbon:
  eureka:
    enabled: true

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
security:
    user:
        name: admin
        password: admin
        role: USER

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#请求和响应GZIP压缩支持
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

gate:
  ignore:
    startWith: /back/menu/user,/admin/index,/admin/about,/admin/main,/admin/login
    contain: .
  oauth:
    prefix: /api

  jwt:
    secret: Xe*g@1jda
    expiration: 7200
    header: access-token
