logging:
    level:
        tk.mybatis: DEBUG
        pers.liuqing.cloudsys.admin: DEBUG
        com.neo.mapper: DEBUG
    config: classpath:logback.xml
    path: /log
spring:
    application:
        name: admin-service
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
   # boot:
   #   admin:
   #     url: http://130.30.3.170:8764/
    boot:
        admin:
             url: http://localhost:8764
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/admin_cloud_db?useUnicode=true&characterEncoding=UTF8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
    basepackage: pers.liuqing.cloudsys.admin.service.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: 8768

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
swagger:
    basepackage: pers.liuqing.cloudsys.admin.service
    service:
        name: Admin Service
        description: Admin Service后端服务
        developer: liuqinga