spring:
    application:
        name: blog-ui
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    boot:
      admin:
        url: http://130.30.3.170:8764/
server:
    port: 8788

eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
back:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
feign:
  hystrix:
      enabled: true